<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-CONTINUE-UW-QUESTIONS</name>
   <tag></tag>
   <elementGuidId>99bbaa9f-b723-4d73-ad9b-b34d38c82a2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnSaveUnderwriting&quot;]</value>
   </webElementProperties>
</WebElementEntity>
