<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-SUBMIT-AGENT-SIGNATURE</name>
   <tag></tag>
   <elementGuidId>21cdcd82-142a-4281-bb53-c5a27b9a34f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnSaveAgentSign&quot;]</value>
   </webElementProperties>
</WebElementEntity>
