<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-VIEW-POLICY-FORMS</name>
   <tag></tag>
   <elementGuidId>169dc0ab-260b-4db8-9955-bc6096f488ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>html/body/div[2]/div[1]/section/div[1]/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>html/body/div[2]/div/section/div[1]/div[2]/form/button</value>
   </webElementProperties>
</WebElementEntity>
