<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp-HEATINGTYPE-PROPERTYPAGE</name>
   <tag></tag>
   <elementGuidId>4b80b03e-3aa2-43c6-b5c1-acad1adb6ca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ddlHeatingType&quot;]</value>
   </webElementProperties>
</WebElementEntity>
