<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield-INSURED-MIDDLENAME</name>
   <tag></tag>
   <elementGuidId>779f4fa4-5919-4069-aba3-4795dd47d4a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtPrimaryMiddleName&quot;]</value>
   </webElementProperties>
</WebElementEntity>
