<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield-INSURED-CONTACTNUMBER</name>
   <tag></tag>
   <elementGuidId>f9fd42b4-bebe-4bf9-9dfd-a5f4713992ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtPrimaryMobileNo&quot;]</value>
   </webElementProperties>
</WebElementEntity>
