<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield_SENDQUOTE_CONTACTNUMBER</name>
   <tag></tag>
   <elementGuidId>3a9a52cc-1855-4281-abde-bdf38d222f46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;txtMob&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@class = 'form-control']) = count(//*[@class = 'form-control'])][count(. | //*[@data-val = 'true']) = count(//*[@data-val = 'true'])][count(. | //*[@data-val-regex = 'Invalid Zip']) = count(//*[@data-val-regex = 'Invalid Zip'])][count(. | //*[@data-val-regex-pattern = '^[1-9]\d{9}$']) = count(//*[@data-val-regex-pattern = '^[1-9]\d{9}$'])][count(. | //*[@data-val-required = 'The Telephone field is required.']) = count(//*[@data-val-required = 'The Telephone field is required.'])][count(. | //*[@id = 'txtMob']) = count(//*[@id = 'txtMob'])][count(. | //*[@maxlength = '13']) = count(//*[@maxlength = '13'])][count(. | //*[@name = 'PropertyInfo.PropertyAddress.MobileNo']) = count(//*[@name = 'PropertyInfo.PropertyAddress.MobileNo'])][count(. | //*[@placeholder = 'Mobile Number']) = count(//*[@placeholder = 'Mobile Number'])][count(. | //*[@type = 'text']) = count(//*[@type = 'text'])][count(. | //*[@value = '9768180080']) = count(//*[@value = '9768180080'])][count(. | id(&quot;txtMob&quot;)) = count(id(&quot;txtMob&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid Zip</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[1-9]\d{9}$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Telephone field is required.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtMob</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PropertyInfo.PropertyAddress.MobileNo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mobile Number</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>9768180080</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtMob&quot;)</value>
   </webElementProperties>
</WebElementEntity>
