<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield_HOME_VALUATION</name>
   <tag></tag>
   <elementGuidId>db5584cd-4602-4203-8733-9e6e79e0e1b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;txtPropertyValuetion&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@class = 'form-control txt valid']) = count(//*[@class = 'form-control txt valid'])][count(. | //*[@data-val = 'true']) = count(//*[@data-val = 'true'])][count(. | //*[@data-val-required = 'The Estimated Valuation field is required.']) = count(//*[@data-val-required = 'The Estimated Valuation field is required.'])][count(. | //*[@id = 'txtPropertyValuetion']) = count(//*[@id = 'txtPropertyValuetion'])][count(. | //*[@maxlength = '11']) = count(//*[@maxlength = '11'])][count(. | //*[@name = 'PropertyInfo.ValuationRangeInfo.ValuationRangeHigh']) = count(//*[@name = 'PropertyInfo.ValuationRangeInfo.ValuationRangeHigh'])][count(. | //*[@type = 'text']) = count(//*[@type = 'text'])][count(. | //*[@value = '100000']) = count(//*[@value = '100000'])][count(. | //*[@title = 'one hundred thousand ']) = count(//*[@title = 'one hundred thousand '])][count(. | id(&quot;txtPropertyValuetion&quot;)) = count(id(&quot;txtPropertyValuetion&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control txt valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Estimated Valuation field is required.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtPropertyValuetion</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PropertyInfo.ValuationRangeInfo.ValuationRangeHigh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>100000</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>one hundred thousand </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtPropertyValuetion&quot;)</value>
   </webElementProperties>
</WebElementEntity>
