<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_View</name>
   <tag></tag>
   <elementGuidId>9b8fccb7-9245-410f-bfd2-ce60a8bc7e44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Grid&quot;]/tbody/tr[1]/td[7]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[count(. | //*[@href = '/RetrieveHistory/GetPolicy?PolicyInfoId=2295']) = count(//*[@href = '/RetrieveHistory/GetPolicy?PolicyInfoId=2295'])][count(. | //*[@class = 'btn btn-primary btn-xs btnViewPolicy']) = count(//*[@class = 'btn btn-primary btn-xs btnViewPolicy'])][count(. | //*[text() = 'View']) = count(//*[text() = 'View'])][count(. | id(&quot;Grid&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary btn-xs btnViewPolicy&quot;]) = count(id(&quot;Grid&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary btn-xs btnViewPolicy&quot;])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/RetrieveHistory/GetPolicy?PolicyInfoId=2295</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-xs btnViewPolicy</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Grid&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;text-center&quot;]/a[@class=&quot;btn btn-primary btn-xs btnViewPolicy&quot;]</value>
   </webElementProperties>
</WebElementEntity>
