<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SUBMIT_INSURED_SIGNATURE</name>
   <tag></tag>
   <elementGuidId>a25ccb58-48c9-47bc-acd0-5d7999c45ae9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnSendOtp&quot;]</value>
   </webElementProperties>
</WebElementEntity>
