<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SEARCH_ADDRESS_QUOTE_PAGE</name>
   <tag></tag>
   <elementGuidId>4fcfff3d-a05b-4341-8fc0-66175d314d9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnSearchAddress&quot;]</value>
   </webElementProperties>
</WebElementEntity>
