<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SUBMIT_HOMEOWNER_END_FORM</name>
   <tag></tag>
   <elementGuidId>59aeea89-b46b-4577-91f3-206022bae010</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnEndorseFormSubmit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
