<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield_POLICYNUMBER_FOR_ENDORSEMENT</name>
   <tag></tag>
   <elementGuidId>8c26b6a5-262f-4220-97d3-486bac09a651</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtPolicyNumber&quot;]</value>
   </webElementProperties>
</WebElementEntity>
