<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_ENDORSEMENT_MENU</name>
   <tag></tag>
   <elementGuidId>0e9d8fd6-0a47-4f41-805e-4a28fc0c4bff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;linkEndorsement&quot;]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;linkEndorsement&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
