<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_UPDATE_APPLICANTINFO_UW</name>
   <tag></tag>
   <elementGuidId>3c5a5d2c-f57c-49aa-aa93-8b61dc3f810e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnUpdateApplicant&quot;]</value>
   </webElementProperties>
</WebElementEntity>
