<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_FILLDATA_HOMEOWNER_END_FORM</name>
   <tag></tag>
   <elementGuidId>16949e0b-6c5c-4c7f-b776-bff962e80005</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnFillData_4021&quot;]</value>
   </webElementProperties>
</WebElementEntity>
