<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_UPDATE_ENDORSEMENT_PROPERTY_UW</name>
   <tag></tag>
   <elementGuidId>f2290408-a200-4744-8cc9-d4b2749500b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnUpdateProperty&quot;]</value>
   </webElementProperties>
</WebElementEntity>
