<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PrimaryApplicant.Applica (1)</name>
   <tag></tag>
   <elementGuidId>a3da72ed-eb69-4984-91b1-1dc26502d8e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;txtLastName&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@class = 'form-control']) = count(//*[@class = 'form-control'])][count(. | //*[@data-val = 'true']) = count(//*[@data-val = 'true'])][count(. | //*[@data-val-length = 'The field Last Name must be a string with a maximum length of 20.']) = count(//*[@data-val-length = 'The field Last Name must be a string with a maximum length of 20.'])][count(. | //*[@data-val-length-max = '20']) = count(//*[@data-val-length-max = '20'])][count(. | //*[@data-val-regex = 'Invalid Last Name']) = count(//*[@data-val-regex = 'Invalid Last Name'])][count(. | //*[@data-val-regex-pattern = '^[A-Za-z '-]+$']) = count(//*[@data-val-regex-pattern = '^[A-Za-z '-]+$'])][count(. | //*[@data-val-required = 'The Last Name field is required.']) = count(//*[@data-val-required = 'The Last Name field is required.'])][count(. | //*[@id = 'txtLastName']) = count(//*[@id = 'txtLastName'])][count(. | //*[@maxlength = '20']) = count(//*[@maxlength = '20'])][count(. | //*[@name = 'PrimaryApplicant.ApplicantName.LastName']) = count(//*[@name = 'PrimaryApplicant.ApplicantName.LastName'])][count(. | //*[@placeholder = 'Last Name']) = count(//*[@placeholder = 'Last Name'])][count(. | //*[@type = 'text']) = count(//*[@type = 'text'])][count(. | //*[@value = 'Salunkhe']) = count(//*[@value = 'Salunkhe'])][count(. | id(&quot;txtLastName&quot;)) = count(id(&quot;txtLastName&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field Last Name must be a string with a maximum length of 20.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid Last Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[A-Za-z '-]+$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Last Name field is required.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLastName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimaryApplicant.ApplicantName.LastName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Salunkhe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLastName&quot;)</value>
   </webElementProperties>
</WebElementEntity>
