<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_SETTLEMENTTYPE_UW</name>
   <tag></tag>
   <elementGuidId>ca29d36f-5804-4df5-a6f6-8d9ed1265e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ddlDeductibleType&quot;]</value>
   </webElementProperties>
</WebElementEntity>
