<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield_HOME_BUILD_ENDORSEMENT_UW</name>
   <tag></tag>
   <elementGuidId>06f1f7c2-4628-4d14-b33a-cb782759740e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtYearHomeBuild&quot;]</value>
   </webElementProperties>
</WebElementEntity>
