<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield_ENDORSEMENTEFFECTIVEDATE_UW</name>
   <tag></tag>
   <elementGuidId>9e1a60d7-0fb8-479b-bd27-e2116eed1d09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;txtEndorseEffectiveDate&quot;]</value>
   </webElementProperties>
</WebElementEntity>
