<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-RECALCULATE-PREMIUM</name>
   <tag></tag>
   <elementGuidId>cfcb4862-d9a5-4739-b54a-c588bf7ae95c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnCalculateQuote&quot;]</value>
   </webElementProperties>
</WebElementEntity>
