<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtfield-SENDQUOTE-FIRSTNAME</name>
   <tag></tag>
   <elementGuidId>fd084cd6-1a6d-42ed-86de-8cb69eb8ee0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;txtFirstName&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@class = 'form-control input-validation-error']) = count(//*[@class = 'form-control input-validation-error'])][count(. | //*[@data-val = 'true']) = count(//*[@data-val = 'true'])][count(. | //*[@data-val-length = 'The field First Name must be a string with a maximum length of 20.']) = count(//*[@data-val-length = 'The field First Name must be a string with a maximum length of 20.'])][count(. | //*[@data-val-length-max = '20']) = count(//*[@data-val-length-max = '20'])][count(. | //*[@data-val-regex = 'Invalid First Name']) = count(//*[@data-val-regex = 'Invalid First Name'])][count(. | //*[@data-val-regex-pattern = '^[A-Za-z '-]+$']) = count(//*[@data-val-regex-pattern = '^[A-Za-z '-]+$'])][count(. | //*[@data-val-required = 'The First Name field is required.']) = count(//*[@data-val-required = 'The First Name field is required.'])][count(. | //*[@id = 'txtFirstName']) = count(//*[@id = 'txtFirstName'])][count(. | //*[@maxlength = '20']) = count(//*[@maxlength = '20'])][count(. | //*[@name = 'PrimaryApplicant.ApplicantName.FirstName']) = count(//*[@name = 'PrimaryApplicant.ApplicantName.FirstName'])][count(. | //*[@placeholder = 'First Name']) = count(//*[@placeholder = 'First Name'])][count(. | //*[@type = 'text']) = count(//*[@type = 'text'])][count(. | //*[@value = 'Ganesh']) = count(//*[@value = 'Ganesh'])][count(. | id(&quot;txtFirstName&quot;)) = count(id(&quot;txtFirstName&quot;))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-validation-error</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The field First Name must be a string with a maximum length of 20.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex</name>
      <type>Main</type>
      <value>Invalid First Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-regex-pattern</name>
      <type>Main</type>
      <value>^[A-Za-z '-]+$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The First Name field is required.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtFirstName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimaryApplicant.ApplicantName.FirstName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>First Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ganesh</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtFirstName&quot;)</value>
   </webElementProperties>
</WebElementEntity>
