<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-YES_FOOT_TRAFFIC</name>
   <tag></tag>
   <elementGuidId>bdba75b7-a2ff-4972-892e-87bd06b503dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;div_4&quot;]/div/div[2]/div/a[1]</value>
   </webElementProperties>
</WebElementEntity>
