<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-YES_IS_BNESS_PREMISES</name>
   <tag></tag>
   <elementGuidId>37c2de03-bde7-4133-885e-b232dfa10db5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;div_3&quot;]/div/div[2]/div/a[1]</value>
   </webElementProperties>
</WebElementEntity>
