<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SUBMIT_FOR_UW_APPROVAL</name>
   <tag></tag>
   <elementGuidId>a4e89ea8-8c49-4284-b8a8-b0233cebf984</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnSubmitForApproval&quot;]</value>
   </webElementProperties>
</WebElementEntity>
