<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SUBMIT_SURPLUSLINE</name>
   <tag></tag>
   <elementGuidId>b6511894-8d6f-494d-94fe-4dbdb07faf58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;btnAgentFormSubmit&quot;]</value>
   </webElementProperties>
</WebElementEntity>
