<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_UW_APPLICATION_STATUS_MENU</name>
   <tag></tag>
   <elementGuidId>c74f1576-069f-4f6b-92af-d9ad08b870d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='linkApplicationStatus']/img[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='linkApplicationStatus']/img[1]</value>
   </webElementProperties>
</WebElementEntity>
