<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>drp_ROOFTYPE_PROPERTYPAGE</name>
   <tag></tag>
   <elementGuidId>02df32ab-56fa-462e-80f3-1db08363b825</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ddlRoofType&quot;]</value>
   </webElementProperties>
</WebElementEntity>
